// array of object literals with data components depicted below
const books = [
    {
        title: "One Piece, Volume 1: Romance Dawn (One Piece, #1)",
        author: "Oda, Eiichiro",
        rating: 4.48,
        publisher: "VIZ Media LLC",
        publicationYear: 2003,
        originalPublicationYear: 1997,
        imgUrl: "https://m.media-amazon.com/images/I/71y+XnBXm4L._AC_UF1000,1000_QL80_.jpg",
        opinion: 4,
        genres: ["manga", "fantasy","     adventure", "action"],
        description: `"As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber…at the cost of never being able to swim again! Years, later, Luffy sets off in search of the “One Piece,” said to be the greatest treasure in the world..."`,
        descriptionSource: "Amazon"
    },
    {
        title: "Red Rising (Red Rising Saga, #1)",
        author: "Brown, Pierce",
        rating: 4.27,
        publisher: "Del Rey",
        publicationYear: 2014,
        originalPublicationYear: 2014,
        imgUrl: "https://m.media-amazon.com/images/I/81tZufOGaZL._AC_UF1000,1000_QL80_.jpg",
        opinion: 4.5,
        genres: ["science fiction", "       dystopian fiction", "novel"],
        description: `"Set in the future on Mars, [it] follows lowborn miner Darrow. The powerful ruling class of humans has installed a rigid, color-based social hierarchy where the physically superior Golds at the top rule with an iron fist. [Watch] as he infiltrates the ranks of the elite Golds."`,
        descriptionSource: "Wikipedia"
    },
    {
        title: "The Bell Jar",
        author: "Plath, Sylvia",
        rating: 4.05,
        publisher: "Harper Perennial Modern Classics",
        publicationYear: 2006,
        originalPublicationYear: 1963,
        imgUrl: "https://www.literaryladiesguide.com/wp-content/uploads/2012/07/Bell-Jar.jpg",
        opinion: 5,
        genres: ["novel", "          autobiography", "psychological fiction"],
        description: `"The Bell Jar chronicles the crack-up of Esther Greenwood: brilliant, beautiful, enormously talented, and successful, but slowly going under—maybe for the last time. Sylvia Plath masterfully draws the reader into Esther's breakdown with such intensity that Esther's insanity becomes completely real and even rational."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Tomorrow, and Tomorrow, and Tomorrow",
        author: "Zevin, Gabrielle",
        rating: 4.18,
        publisher: "Knopf",
        publicationYear: 2022,
        originalPublicationYear: 2022,
        imgUrl: "https://m.media-amazon.com/images/I/91VcwLdcNHL._AC_UF1000,1000_QL80_.jpg",
        opinion: 1,
        genres: ["coming-of-age", "adventure fiction"],
        description: `"In this exhilarating novel, two friends—often in love, but never lovers—come together as creative partners in the world of video game design, where success brings them fame, joy, tragedy, duplicity, and, ultimately, a kind of immortality."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "The Midnight Library",
        author: "Haig, Matt",
        rating: 4,
        publisher: "Viking",
        publicationYear: 2020,
        originalPublicationYear: 2020,
        imgUrl: "https://m.media-amazon.com/images/I/71ls-I6A5KL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["science fiction", "fantasy fiction", "philosophical fiction"],
        description: `"Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. Would you have done anything different, if you had the chance to undo your regrets? A novel about all the choices that go into a life well lived."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "A Timeless Story: Man's Search for Meaning by V.E. Frankl's Memoir",
        author: "Frankl, Viktor E.",
        rating: 4.37,
        publisher: "",
        publicationYear: 2021,
        originalPublicationYear: 1959,
        imgUrl: "https://m.media-amazon.com/images/I/61nTspM+BYL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["biography", "     autobiography", "        personal narrative"],
        description: `"Psychiatrist V.E.Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Between 1942 and 1945 Frankl labored in four different camps, including Auschwitz, while his parents, brother, and pregnant wife perished."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Reid, Taylor Jenkins",
        rating: 4.42,
        publisher: "Atria Books",
        publicationYear: 2017,
        originalPublicationYear: 2017,
        imgUrl: "https://m.media-amazon.com/images/I/71KcUgYanhL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3,
        genres: ["novel", "romance novel", "historical fiction"],
        description: `"Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her? Why now?"`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Grasshopper Jungle",
        author: "Smith, Andrew",
        rating: 3.63,
        publisher: "Dutton Books",
        publicationYear: 2014,
        originalPublicationYear: 2014,
        imgUrl: "https://m.media-amazon.com/images/I/61wUv6fkRPL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3,
        genres: ["humor", "novel", "science fiction"],
        description: `"Sixteen-year-old Austin Szerba interweaves the story of his Polish legacy with the story of how he and his best friend, Robby, brought about the end of humanity and the rise of an army of unstoppable, six-foot tall praying mantises in small-town Iowa."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Flipped",
        author: "Van Draanen, Wendelin",
        rating: 3.98,
        publisher: "Knopf",
        publicationYear: 2003,
        originalPublicationYear: 2001,
        imgUrl: "https://m.media-amazon.com/images/I/51Hzxs85pTL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["young adult literature", "romance novel"],
        description: `"The first time she saw him, she flipped. The first time he saw her, he ran. But in the eighth grade everything gets turned upside down: just as Bryce is thinking that there’s maybe more to Juli than meets the eye, she’s thinking that he’s not quite all he seemed."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Hatchet (Brian's Saga, #1)",
        author: "Paulsen, Gary",
        rating: 3.78,
        publisher: "Atheneum Books for Young Readers: Richard Jackson Books",
        publicationYear: 2000,
        originalPublicationYear: 1987,
        imgUrl: "https://m.media-amazon.com/images/I/81TZunL8kQL._AC_UF1000,1000_QL80_.jpg",
        opinion: 4,
        genres: ["novel", "young adult literature", "adventure fiction"],
        description: `"On his way to visit his recently divorced father in the Canadian mountains, thirteen-year-old Brian Robeson is the only survivor when the single-engine plane crashes. His body battered, his clothes in shreds, Brian must now stay alive in the boundless Canadian wilderness."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Fahrenheit 451",
        author: "Bradbury, Ray",
        rating: 3.97,
        publisher: "Simon & Schuster",
        publicationYear: 2011,
        originalPublicationYear: 1953,
        imgUrl: "https://m.media-amazon.com/images/I/61z7RDG3OIL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["novel", "dystopian fiction", "political fiction"],
        description: `"Fahrenheit 451 is an essential read for everyone. Bradbury’s disturbing dystopian novel stresses the dangers of willful ignorance and the censorship of knowledge. Ray Bradbury’s writing is stunning, and the grim future he had predicted is a haunting image that will never fade from your mind."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "The Giver (The Giver, #1)",
        author: "Lowry, Lois",
        rating: 4.12,
        publisher: "Ember",
        publicationYear: 2006,
        originalPublicationYear: 1993,
        imgUrl: "https://m.media-amazon.com/images/I/81cJChEQjSL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3.5,
        genres: ["novel", "science fiction", "dystopian fiction"],
        description: `"Life in the community is idyllic. [Jonas] is given his life assignment as the Receiver of Memory does he begin to understand the dark, complex secrets behind his fragile community. Gradually Jonas learns that power lies in feelings. But when his own power is put to the test—when he must try to save someone he loves—he may not be ready."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "A Darker Shade of Magic (Shades of Magic, #1)",
        author: "Schwab, V.E.",
        rating: 4.06,
        publisher: "Tor",
        publicationYear: 2015,
        originalPublicationYear: 2015,
        imgUrl: "https://m.media-amazon.com/images/I/81Zd2d+NMZL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["fantasy", "science fiction", "historical fantasy"],
        description: `"Kell is one of the last Antari―magicians with a rare, coveted ability to travel between parallel Londons; Red, Grey, White, and, once upon a time, Black. Unofficially, Kell is a smuggler, servicing people willing to pay for even the smallest glimpses of a world they'll never see. It's a defiant hobby with dangerous consequences, which Kell is now seeing firsthand."`,
        descriptionSource: "Amazon"
    },
    {
        title: "Of Mice and Men",
        author: "Steinbeck, John",
        rating: 3.88,
        publisher: "Penguin Books",
        publicationYear: 2002,
        originalPublicationYear: 1937,
        imgUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Of_Mice_and_Men_%281937_1st_ed_dust_jacket%29.jpg",
        opinion: 5,
        genres: ["novella", "fiction", "tragedy"],
        description: `"They are an unlikely pair: George is "small and quick and dark of face"; Lennie, a man of tremendous size, has the mind of a young child. Yet they have formed a "family," clinging together in the face of loneliness and alienation. Laborers in California's dusty vegetable fields, they hustle work when they can, living a hand-to-mouth existence."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "1984",
        author: "Orwell, George",
        rating: 4.19,
        publisher: "Houghton Mifflin Harcourt",
        publicationYear: 2013,
        originalPublicationYear: 1949,
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEZOB8G9WhHl2MjHjktqreA5NENS2vsoCJesh8lcjB_w&s",
        opinion: 3,
        genres: ["dystopian fiction", "political fiction", "science fiction"],
        description: `"Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching..."`,
        descriptionSource: "Amazon"
    },
    {
        title: "The Great Gatsby",
        author: "Fitzgerald, F. Scott",
        rating: 3.93,
        publisher: "Scribner",
        publicationYear: 1925,
        originalPublicationYear: 1925,
        imgUrl: "https://m.media-amazon.com/images/I/61OTNorhqVS._AC_UF894,1000_QL80_.jpg",
        opinion: 3,
        genres: ["novel", "tragedy", "literary fiction"],
        description: `"The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante, #1)",
        author: "Sáenz, Benjamin Alire",
        rating: 4.31,
        publisher: "Simon & Schuster Books for Young Readers",
        publicationYear: 2012,
        originalPublicationYear: 2012,
        imgUrl: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781665955751/aristotle-and-dante-discover-the-secrets-of-the-universe-9781665955751_hr.jpg",
        opinion: 3,
        genres: ["novel", "young adult literature", "Bildungsroman"],
        description: `"Aristotle is an angry teen with a brother in prison. Dante is a know-it-all who has an unusual way of looking at the world. When the two meet at the swimming pool, they seem to have nothing in common. But as the loners start spending time together, they discover that they share a special friendship—the kind that changes lives and lasts a lifetime."`,
        descriptionSource: "Amazon"
    },
    {
        title: "One of Us Is Lying (One of Us is Lying, #1)",
        author: "McManus, Karen M.",
        rating: 3.94,
        publisher: "Delacorte Press",
        publicationYear: 2017,
        originalPublicationYear: 2017,
        imgUrl: "https://m.media-amazon.com/images/I/914W0VECGCL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3,
        genres: ["young adult literature", "mystery"],
        description: `"On Monday afternoon, five students at Bayview High walk into detention. Before the end of detention Simon's dead. And according to investigators, his death wasn’t an accident."`,
        descriptionSource: "Amazon"
    },
    {
        title: "They Both Die at the End (They Both Die at the End Series, 1)",
        author: "Silvera, Adam",
        rating: 3.77,
        publisher: "Quill Tree Books",
        publicationYear: 2017,
        originalPublicationYear: 2017,
        imgUrl: "https://m.media-amazon.com/images/I/81D-gdnku+L._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["young adult literature", "LGBT literature"],
        description: `"Deeply profound and incredibly heartbreaking, They Both Die at the End answers the question, “What would you do if you only had one day to live?” Silvera’s lyrical writing transports readers to a New York City where at any moment Death can call."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "We Are the Ants",
        author: "Hutchinson, Shaun David",
        rating: 4.12,
        publisher: "Simon Pulse",
        publicationYear: 2016,
        originalPublicationYear: 2016,
        imgUrl: "https://m.media-amazon.com/images/I/71KJo78F-fL._SL1500_.jpg",
        opinion: 5,
        genres: ["young adult literature", "science fiction"],
        description: `"Henry Denton has spent years being periodically abducted by aliens. The aliens give him an ultimatum: The world will end in 144 days, and all Henry has to do to stop it is push a big red button. Only he isn’t sure he wants to."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Maybe You Should Talk to Someone",
        author: "Gottlieb, Lori",
        rating: 4.38,
        publisher: "Harper",
        publicationYear: 2019,
        originalPublicationYear: 2019,
        imgUrl: "https://m.media-amazon.com/images/I/71r0hQEoWIL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["memoir", "autobiography", "        biography"],
        description: `"From a psychotherapist, and national advice columnist comes a thought-provoking new book that takes us behind the scenes of a therapist's world -- where her patients are looking for answers (and so is she)."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "The Night Circus",
        author: "Morgenstern, Erin",
        rating: 4.02,
        publisher: "Doubleday",
        publicationYear: 2011,
        originalPublicationYear: 2011,
        imgUrl: "https://m.media-amazon.com/images/I/81dAQFi5HzL._AC_UF1000,1000_QL80_.jpg",
        opinion: 1,
        genres: ["novel", "fantasy", "      romance"],
        description:  `"The circus arrives without warning. [B]ehind the scenes, a fierce competition is underway: a duel between two young magicians, Celia and Marco, who have been trained since childhood expressly for this purpose by their mercurial instructors. Unbeknownst to them both, this is a game in which only one can be left standing."`,
        descriptionSource: "Wikipedia"
    },
    {
        title: "The Hate U Give (The Hate U Give, #1)",
        author: "Thomas, Angie",
        rating: 4.48,
        publisher: "Balzer + Bray",
        publicationYear: 2017,
        originalPublicationYear: 2017,
        imgUrl: "https://m.media-amazon.com/images/I/71DZv5+s67L._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["novel", "urban fiction"],
        description: `"Caught between two worlds, Starr is the sole witness when police murder her unarmed best friend, leaving her stuck debating right and wrong, what to do and what not to do. In a story that speaks directly to the recent string of such cases, this book is sure to remind readers of the work we still have to do in this world."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Lord of the Flies",
        author: "Golding, William",
        rating: 3.69,
        publisher: "Penguin Books",
        publicationYear: 1999,
        originalPublicationYear: 1954,
        imgUrl: "https://images.penguinrandomhouse.com/cover/9780143129400",
        opinion: 4.5,
        genres: ["novel", "allegory", "young adult literature"],
        description: `"At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. This far from civilization they can do anything they want. Anything. But as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far removed from reality as the hope of being rescued."`,
        descriptionSource: "Amazon"
    },
    {
        title: "The Handmaid's Tale (The Handmaid's Tale, #1)",
        author: "Atwood, Margaret",
        rating: 4.14,
        publisher: "Anchor Books",
        publicationYear: 1998,
        originalPublicationYear: 1985,
        imgUrl: "https://m.media-amazon.com/images/I/61su39k8NUL._AC_UF1000,1000_QL80_.jpg",
        opinion: 4.5,
        genres: ["novel", "dystopian fiction", "feminist science fiction"],
        description: `"Set in the religious patriarchy of Gilead, The Handmaid's Tale is a haunting narrative of what America could be. As the threat of Gilead looms ever closer, this seems less like a dystopian novel and more like a prescient warning. Read it before you live it."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "The Girl on the Train",
        author: "Hawkins, Paul",
        rating: 3.96,
        publisher: "Riverhead Books",
        publicationYear: 2015,
        originalPublicationYear: 2015,
        imgUrl: "https://m.media-amazon.com/images/I/41t6xrKxxPL._SY445_SX342_.jpg",
        opinion: 5,
        genres: ["novel", "thriller", "mystery"],
        description: `"Every day [Rachel] rattles down the track, flashes past a stretch of cozy suburban homes, and stops at the signal that allows her to daily watch the same couple breakfasting on their deck. And then she sees something shocking. It’s only a minute until the train moves on, but it’s enough. Now everything’s changed."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Eleanor & Park",
        author: "Rowell, Rainbow",
        rating: 3.94,
        publisher: "St. Martin's Press",
        publicationYear: 2013,
        originalPublicationYear: 2012,
        imgUrl: "https://m.media-amazon.com/images/I/71CY50T1sML._AC_UF1000,1000_QL80_.jpg",
        opinion: 1,
        genres: ["novel", "fiction", "romance"],
        description: `"Eleanor, a chubby 16-year-old girl with curly red hair, and Park, a 16-year-old biracial Korean boy, meet on a school bus on Eleanor's first day at the school and gradually connect through comic books and mixtapes of 1980s music, sparking a love story."`,
        descriptionSource: "Wikipedia"
    },
    {
        title: "The Hunger Games (The Hunger Games, #1)",
        author: "Collins, Suzanne",
        rating: 4.34,
        publisher: "Scholastic Press",
        publicationYear: 2008,
        originalPublicationYear: 2008,
        imgUrl: "https://m.media-amazon.com/images/I/71un2hI4mcL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3,
        genres:["novel", "young adult literature", "dystopian fiction"],
        description: `"[T]here can only be one survivor. Katniss Everdeen is a reluctant tribute in the 74th Hunger Games, volunteering to take the place of her younger sister. As Katniss enters the arena, she must decide how she’s going to survive, even if it means killing her fellow contestants."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Every Day (Every Day, #1)",
        author: "Leviathan, David",
        rating: 3.9,
        publisher: "Knopf Books for Young Readers",
        publicationYear: 2012,
        originalPublicationYear: 2012,
        imgUrl: "https://m.media-amazon.com/images/I/81f3kki57fL._AC_UF1000,1000_QL80_.jpg",
        opinion: 3,
        genres: ["novel", "young adult literature", "romance novel"],
        description: `"Every Day is about the story of A, a genderless person who wakes up occupying a different body each day of a sixteen-year-old living in the East Coast. "`,
        descriptionSource: "Wikipedia"
    },
    {
        title: "Me Before You (Me Before You, #1)",
        author: "Moyes, Jojo",
        rating: 4.26,
        publisher: "Penguin Books",
        publicationYear: 2013,
        originalPublicationYear: 2012,
        imgUrl: "https://m.media-amazon.com/images/I/61Ax4eSeTDL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["romance novel", "fiction", "contemporary romance"],
        description: `"A Love Story for this generation and perfect for fans of John Green’s The Fault in Our Stars, Me Before You brings to life two people who couldn’t have less in common—a heartbreakingly romantic novel that asks, 'What do you do when making the person you love happy also means breaking your own heart?'"`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Chainsaw Man, Vol. 1: Dog and Chainsaw",
        author: "Fujimoto, Tatsuki",
        rating: 4.39,
        publisher: "VIZ Media LLC",
        publicationYear: 2020,
        originalPublicationYear: 2019,
        imgUrl: "https://m.media-amazon.com/images/I/81s8xJUzWGL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["shonen", "dark fantasy", "manga"],
        description: `"Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil-dog Pochita. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!"`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Mob Psycho 100 Volume 1",
        author: "ONE",
        rating: 4.22,
        publisher: "Dark Horse Comics",
        publicationYear: 2012,
        originalPublicationYear: 2012,
        imgUrl: "https://m.media-amazon.com/images/I/91nunbvU04L._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["action", "comedy", "          supernatural", "     manga"],
        description: `"Shigeo Kageyama is an average middle school-aged boy, nicknamed Mob. [However], he is in fact a powerful esper with immense psychic power. To keep from losing control of this power, he constantly lives a life under an emotional shackle. Mob wants to live a normal life just like those around him, but a barrage of trouble keeps coming after him."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Goodnight PunPun Omnibus, Vol. 1 (Goodnight Punpun, Omnibus #1)",
        author: "Asano, Inio",
        rating: 4.27,
        publisher: "VIZ Media LLC",
        publicationYear: 2016,
        originalPublicationYear: 2016,
        imgUrl: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449607528i/25986929.jpg",
        opinion: 5,
        genres: ["seinen", "drama", "manga"],
        description: `"This is Punpun Onodera’s coming-of-age story. His parents’ marriage is falling apart. His dad goes to jail, and his mom goes to the hospital. He has to live with his loser uncle. He has a crush on a girl who lives in a weird cult. Punpun tries talking with God about his problems, but God is a jerk. Punpun keeps hoping things will get better, but they really, really don’t."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "I'm Glad My Mom Died",
        author: "McCurdy, Jennette",
        rating: 4.47,
        publisher: "Simon & Schuster",
        publicationYear: 2022,
        originalPublicationYear: 2022,
        imgUrl: "https://m.media-amazon.com/images/I/71x3UZ18tmL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["memoir", "        autobiography", "biography"],
        description: `"Readers get the chance to learn how 'the industry' really works, as Jennette describes what it's like as a child star, further fueling the narrative, of late, around how victimizing Hollywood can be. Jennette is direct, honest and hilarious, and despite it all, delivers an inspiring story of resilience and recovery."`,
        descriptionSource: "Barnes & Noble"
    },
    {
        title: "Once Upon a Marigold (Upon a Marigold #1)",
        author: "Ferris, Jean",
        rating: 4.01,
        publisher: "Harcourt, Inc",
        publicationYear: 2004,
        originalPublicationYear: 2002,
        imgUrl: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1429468490i/157055.jpg",
        opinion: 4,
        genres: ["fiction", "humor", "fantasy"],
        description: `"Christian is gaga for Princess Marigold. But he's just a commoner, and no match for royalty. Heck, he lives in a cave with a troll! And now he's discovered another reason to put his love-soggy heart on. Queen Olympia is scheming to take over the kingdom--and she'll bump off her own daughter to do it. Can Christian foil her diabolical plans?"`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Perks of Being a Wallflower",
        author: "Chbosky, Stephen",
        rating: 4.23,
        publisher: "MTV Books/Pocket Books",
        publicationYear: 1999,
        originalPublicationYear: 1999,
        imgUrl: "https://m.media-amazon.com/images/I/81I7vXqjEML._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["Bildungsroman", "young adult literature", "epistolary novel"],
        description: `"This is the story of what it's like to grow up in high school. More intimate than a diary, Charlie's letters are singular and unique, hilarious and devastating. Caught between trying to live his life and trying to run from it puts him on a strange course through uncharted territory. The world of first dates and mixed tapes, family dramas and new friends."`,
        descriptionSource: "GoodReads"
    },
    {
        title: "Sold",
        author: "McCormick, Patricia",
        rating: 4.23,
        publisher: "Little Brown Books for Young Readers",
        publicationYear: 2006,
        originalPublicationYear: 2006,
        imgUrl: "https://m.media-amazon.com/images/I/61NiFw4L1YL._AC_UF1000,1000_QL80_.jpg",
        opinion: 5,
        genres: ["novel", "fiction"],
        description: `"The powerful, poignant, bestselling National Book Award finalist gives voice to a young girl robbed of her childhood yet determined to find the strength to triumph."`,
        descriptionSource: "Barnes & Noble"
    }
];

export default books;

